### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Hate9** [EvaisaDev/noita-online#11]
Does this work on Linux/Steamdeck?

**Comment by dextercd** [comment]
Yes, I use it on Linux as do others. It works exactly the same as on Windows since it's all handled by the Proton compatibility layer.

If you have trouble setting up the mod then I suggest you visit the [Noita Online Discord server](https://discord.com/invite/zJyUSHGcme) and ask for help there. You can also get access to a newer "lab rat" version there.
